// Generated by scripts/generate-navigation.mjs. Do not edit by hand.

const enBookSidebar = [
  {
    "text": "Start reading",
    "items": [
      {
        "text": "Thinking in F#",
        "link": "/en/"
      },
      {
        "text": "Preface: How to Use This Book",
        "link": "/en/preface/"
      }
    ]
  },
  {
    "text": "Part I · Expressions and functions",
    "collapsed": true,
    "items": [
      {
        "text": "Chapter 1: A First F# Session",
        "link": "/en/part-01/ch-01-first-session"
      },
      {
        "text": "Chapter 2: Values, Bindings, and Expressions",
        "link": "/en/part-01/ch-02-values-bindings-expressions"
      },
      {
        "text": "Chapter 3: Functions Are Values",
        "link": "/en/part-01/ch-03-functions-as-values"
      },
      {
        "text": "Chapter 4: Branching and Basic Patterns",
        "link": "/en/part-01/ch-04-branching-patterns"
      },
      {
        "text": "Chapter 5: Lists, Pipelines, and Data Flow",
        "link": "/en/part-01/ch-05-lists-pipelines"
      },
      {
        "text": "Chapter 6: Recursion, Tail Calls, and Folds",
        "link": "/en/part-01/ch-06-recursion-folds"
      }
    ]
  },
  {
    "text": "Part II · Modeling with types",
    "collapsed": true,
    "items": [
      {
        "text": "Chapter 7: Records, Updates, Equality, and Comparison",
        "link": "/en/part-02/ch-07-records-equality"
      },
      {
        "text": "Chapter 8: Discriminated Unions and State Modeling",
        "link": "/en/part-02/ch-08-discriminated-unions"
      },
      {
        "text": "Chapter 9: Absence and Expected Failure",
        "link": "/en/part-02/ch-09-option-result"
      },
      {
        "text": "Chapter 10: Recursive Types and Structural Recursion",
        "link": "/en/part-02/ch-10-recursive-types"
      },
      {
        "text": "Chapter 11: Generics, Constraints, and Units",
        "link": "/en/part-02/ch-11-generics-constraints"
      },
      {
        "text": "Chapter 12: Making Illegal States Unrepresentable",
        "link": "/en/part-02/ch-12-making-illegal-states-unrepresentable"
      }
    ]
  },
  {
    "text": "Part III · Composition and program structure",
    "collapsed": true,
    "items": [
      {
        "text": "Chapter 13: Composition, Argument Order, and Pipeline APIs",
        "link": "/en/part-03/ch-13-composition-pipeline-api"
      },
      {
        "text": "Chapter 14: Choosing Collections and Evaluation Models",
        "link": "/en/part-03/ch-14-collections-evaluation"
      },
      {
        "text": "Chapter 15: Active Patterns and Domain Matching Boundaries",
        "link": "/en/part-03/ch-15-active-patterns"
      },
      {
        "text": "Chapter 16: Modules, Namespaces, Projects, and Compiler Settings",
        "link": "/en/part-03/ch-16-modules-namespaces-projects"
      },
      {
        "text": "Chapter 17: Signatures, Access Control, and F#-Facing APIs",
        "link": "/en/part-03/ch-17-signatures-encapsulation"
      },
      {
        "text": "Chapter 18: Explicit Workflow Composition and Validation Accumulation",
        "link": "/en/part-03/ch-18-workflow-validation"
      }
    ]
  },
  {
    "text": "Part IV · Effects, asynchrony, and concurrency",
    "collapsed": true,
    "items": [
      {
        "text": "Chapter 19: .NET APIs and Null Boundaries",
        "link": "/en/part-04/ch-19-dotnet-null-boundaries"
      },
      {
        "text": "Chapter 20: Functional Core and Effect Boundaries",
        "link": "/en/part-04/ch-20-functional-core-effects"
      },
      {
        "text": "Chapter 21: Exceptions, Resources, and I/O",
        "link": "/en/part-04/ch-21-exceptions-resources-io"
      },
      {
        "text": "Chapter 22: Async<'T> and Task<'T>",
        "link": "/en/part-04/ch-22-async-task"
      },
      {
        "text": "Chapter 23: Cancellation, Timeouts, Faults, and Disposal",
        "link": "/en/part-04/ch-23-cancellation-timeouts"
      },
      {
        "text": "Chapter 24: Parallelism, Concurrency, Agents, and Controlled Mutation",
        "link": "/en/part-04/ch-24-concurrency-agents-state"
      }
    ]
  },
  {
    "text": "Part V · .NET interop and engineering quality",
    "collapsed": true,
    "items": [
      {
        "text": "Chapter 25: Defining Objects in F#",
        "link": "/en/part-05/ch-25-objects-interfaces"
      },
      {
        "text": "Chapter 26: Deeper .NET Boundaries",
        "link": "/en/part-05/ch-26-dotnet-runtime-boundaries"
      },
      {
        "text": "Chapter 27: Designing F# APIs for C#",
        "link": "/en/part-05/ch-27-fsharp-api-for-csharp"
      },
      {
        "text": "Chapter 28: Example Tests, Test Doubles, and Boundary Tests",
        "link": "/en/part-05/ch-28-testing-boundaries"
      },
      {
        "text": "Chapter 29: Property Testing with FsCheck",
        "link": "/en/part-05/ch-29-property-testing"
      },
      {
        "text": "Chapter 30: Diagnostics, Debugging, Formatting, and Builds",
        "link": "/en/part-05/ch-30-diagnostics-tooling-builds"
      },
      {
        "text": "Chapter 31: Measure Before Optimizing",
        "link": "/en/part-05/ch-31-measure-before-optimizing"
      },
      {
        "text": "Chapter 32: From Functions to Applications",
        "link": "/en/part-05/ch-32-functions-to-applications"
      }
    ]
  },
  {
    "text": "Part VI · The booking system",
    "collapsed": true,
    "items": [
      {
        "text": "Chapter 33: Business Language, Commands, Events, and Model",
        "link": "/en/part-06/ch-33-domain-language-model"
      },
      {
        "text": "Chapter 34: The Pure Booking Workflow and Validation",
        "link": "/en/part-06/ch-34-pure-booking-workflow"
      },
      {
        "text": "Chapter 35: Ports, Persistence, Configuration, and Stubs",
        "link": "/en/part-06/ch-35-ports-persistence-config"
      },
      {
        "text": "Chapter 36: Web API, JSON, and Input Boundaries",
        "link": "/en/part-06/ch-36-web-api-boundaries"
      },
      {
        "text": "Chapter 37: Consistency, Idempotency, Retries, and Partial Failure",
        "link": "/en/part-06/ch-37-consistency-idempotency"
      },
      {
        "text": "Chapter 38: Integration, Diagnostics, C# Client, and Release Evidence",
        "link": "/en/part-06/ch-38-integration-diagnostics-release"
      }
    ]
  },
  {
    "text": "Part VII · The ecosystem map",
    "collapsed": true,
    "items": [
      {
        "text": "Chapter 39: ASP.NET Core and the F# Web Ecosystem",
        "link": "/en/part-07/ch-39-web-ecosystem"
      },
      {
        "text": "Chapter 40: Data, Type Providers, Analytics, and Machine Learning",
        "link": "/en/part-07/ch-40-data-analytics"
      },
      {
        "text": "Chapter 41: Fable, Elmish, and Browser Applications",
        "link": "/en/part-07/ch-41-fable-elmish"
      },
      {
        "text": "Chapter 42: Cloud, Containers, Serverless, and .NET Aspire",
        "link": "/en/part-07/ch-42-cloud-containers-aspire"
      },
      {
        "text": "Chapter 43: Avalonia, Desktop, and Mobile",
        "link": "/en/part-07/ch-43-avalonia-desktop-mobile"
      },
      {
        "text": "Chapter 44: Unity 6.3 LTS and F#",
        "link": "/en/part-07/ch-44-unity"
      },
      {
        "text": "Chapter 45: Scripting, Automation, Packages, and What Comes Next",
        "link": "/en/part-07/ch-45-scripting-packages-next"
      }
    ]
  },
  {
    "text": "Reference",
    "collapsed": true,
    "items": [
      {
        "text": "Appendix A: Cross-Platform Setup",
        "link": "/en/appendices/a-setup"
      },
      {
        "text": "Appendix B: Syntax and Operator Quick Reference",
        "link": "/en/appendices/b-syntax-reference"
      },
      {
        "text": "Appendix C: Collection Choice and Complexity",
        "link": "/en/appendices/c-collections"
      },
      {
        "text": "Appendix D: C# to F# Migration and Interop",
        "link": "/en/appendices/d-csharp-migration"
      },
      {
        "text": "Appendix E: Common Compiler Diagnostic Index",
        "link": "/en/appendices/e-compiler-errors"
      },
      {
        "text": "Appendix F: English–Chinese F# Glossary",
        "link": "/en/glossary"
      },
      {
        "text": "Appendix G: Solutions and Open-Exercise Review Guide",
        "link": "/en/appendices/g-solutions-guide"
      },
      {
        "text": "Appendix H: Advanced Feature Recognition Index",
        "link": "/en/appendices/h-advanced-index"
      }
    ]
  }
] as const

const enSolutionsSidebar = [
  {
    "text": "Solutions",
    "items": [
      {
        "text": "Appendix G: Solutions and Open-Exercise Review Guide",
        "link": "/en/appendices/g-solutions-guide"
      },
      {
        "text": "Chapter 1 Solutions",
        "link": "/en/solutions/ch-01-first-session"
      },
      {
        "text": "Chapter 2 Solutions",
        "link": "/en/solutions/ch-02-values-bindings-expressions"
      },
      {
        "text": "Chapter 3 Solutions",
        "link": "/en/solutions/ch-03-functions-as-values"
      },
      {
        "text": "Chapter 4 Solutions",
        "link": "/en/solutions/ch-04-branching-patterns"
      },
      {
        "text": "Chapter 5 Solutions",
        "link": "/en/solutions/ch-05-lists-pipelines"
      },
      {
        "text": "Chapter 6 Solutions",
        "link": "/en/solutions/ch-06-recursion-folds"
      },
      {
        "text": "Chapter 7 Solutions",
        "link": "/en/solutions/ch-07-records-equality"
      },
      {
        "text": "Chapter 8 Solutions",
        "link": "/en/solutions/ch-08-discriminated-unions"
      },
      {
        "text": "Chapter 9 Solutions",
        "link": "/en/solutions/ch-09-option-result"
      },
      {
        "text": "Chapter 10 Solutions",
        "link": "/en/solutions/ch-10-recursive-types"
      },
      {
        "text": "Chapter 11 Solutions",
        "link": "/en/solutions/ch-11-generics-constraints"
      },
      {
        "text": "Chapter 12 Solutions",
        "link": "/en/solutions/ch-12-making-illegal-states-unrepresentable"
      },
      {
        "text": "Chapter 13 Solutions",
        "link": "/en/solutions/ch-13-composition-pipeline-api"
      },
      {
        "text": "Chapter 14 Solutions",
        "link": "/en/solutions/ch-14-collections-evaluation"
      },
      {
        "text": "Chapter 15 Solutions",
        "link": "/en/solutions/ch-15-active-patterns"
      },
      {
        "text": "Chapter 16 Solutions",
        "link": "/en/solutions/ch-16-modules-namespaces-projects"
      },
      {
        "text": "Chapter 17 Solutions",
        "link": "/en/solutions/ch-17-signatures-encapsulation"
      },
      {
        "text": "Chapter 18 Solutions",
        "link": "/en/solutions/ch-18-workflow-validation"
      },
      {
        "text": "Chapter 19 Solutions",
        "link": "/en/solutions/ch-19-dotnet-null-boundaries"
      },
      {
        "text": "Chapter 20 Solutions",
        "link": "/en/solutions/ch-20-functional-core-effects"
      },
      {
        "text": "Chapter 21 Solutions",
        "link": "/en/solutions/ch-21-exceptions-resources-io"
      },
      {
        "text": "Chapter 22 Solutions",
        "link": "/en/solutions/ch-22-async-task"
      },
      {
        "text": "Chapter 23 Solutions",
        "link": "/en/solutions/ch-23-cancellation-timeouts"
      },
      {
        "text": "Chapter 24 Solutions",
        "link": "/en/solutions/ch-24-concurrency-agents-state"
      },
      {
        "text": "Chapter 25 Solutions",
        "link": "/en/solutions/ch-25-objects-interfaces"
      },
      {
        "text": "Chapter 26 Solutions",
        "link": "/en/solutions/ch-26-dotnet-runtime-boundaries"
      },
      {
        "text": "Chapter 27 Solutions",
        "link": "/en/solutions/ch-27-fsharp-api-for-csharp"
      },
      {
        "text": "Chapter 28 Solutions",
        "link": "/en/solutions/ch-28-testing-boundaries"
      },
      {
        "text": "Chapter 29 Solutions",
        "link": "/en/solutions/ch-29-property-testing"
      },
      {
        "text": "Chapter 30 Solutions",
        "link": "/en/solutions/ch-30-diagnostics-tooling-builds"
      },
      {
        "text": "Chapter 31 Solutions",
        "link": "/en/solutions/ch-31-measure-before-optimizing"
      },
      {
        "text": "Chapter 32 Solutions",
        "link": "/en/solutions/ch-32-functions-to-applications"
      },
      {
        "text": "Chapter 33 Solutions",
        "link": "/en/solutions/ch-33-domain-language-model"
      },
      {
        "text": "Chapter 34 Solutions",
        "link": "/en/solutions/ch-34-pure-booking-workflow"
      },
      {
        "text": "Chapter 35 Solutions",
        "link": "/en/solutions/ch-35-ports-persistence-config"
      },
      {
        "text": "Chapter 36 Solutions",
        "link": "/en/solutions/ch-36-web-api-boundaries"
      },
      {
        "text": "Chapter 37 Solutions",
        "link": "/en/solutions/ch-37-consistency-idempotency"
      },
      {
        "text": "Chapter 38 Solutions",
        "link": "/en/solutions/ch-38-integration-diagnostics-release"
      },
      {
        "text": "Chapter 39 Solutions",
        "link": "/en/solutions/ch-39-web-ecosystem"
      },
      {
        "text": "Chapter 40 Solutions",
        "link": "/en/solutions/ch-40-data-analytics"
      },
      {
        "text": "Chapter 41 Solutions",
        "link": "/en/solutions/ch-41-fable-elmish"
      },
      {
        "text": "Chapter 42 Solutions",
        "link": "/en/solutions/ch-42-cloud-containers-aspire"
      },
      {
        "text": "Chapter 43 Solutions",
        "link": "/en/solutions/ch-43-avalonia-desktop-mobile"
      },
      {
        "text": "Chapter 44 Solutions",
        "link": "/en/solutions/ch-44-unity"
      },
      {
        "text": "Chapter 45 Solutions",
        "link": "/en/solutions/ch-45-scripting-packages-next"
      }
    ]
  }
] as const

export const enNavigation = {
  nav: [
    {
      "text": "Home",
      "link": "/en/"
    },
    {
      "text": "Preface and reading routes",
      "link": "/en/preface/"
    },
    {
      "text": "Start reading",
      "link": "/en/part-01/ch-01-first-session"
    },
    {
      "text": "Reference",
      "items": [
        {
          "text": "Appendix A: Cross-Platform Setup",
          "link": "/en/appendices/a-setup"
        },
        {
          "text": "Appendix B: Syntax and Operator Quick Reference",
          "link": "/en/appendices/b-syntax-reference"
        },
        {
          "text": "Appendix C: Collection Choice and Complexity",
          "link": "/en/appendices/c-collections"
        },
        {
          "text": "Appendix D: C# to F# Migration and Interop",
          "link": "/en/appendices/d-csharp-migration"
        },
        {
          "text": "Appendix E: Common Compiler Diagnostic Index",
          "link": "/en/appendices/e-compiler-errors"
        },
        {
          "text": "Appendix F: English–Chinese F# Glossary",
          "link": "/en/glossary"
        },
        {
          "text": "Appendix G: Solutions and Open-Exercise Review Guide",
          "link": "/en/appendices/g-solutions-guide"
        },
        {
          "text": "Appendix H: Advanced Feature Recognition Index",
          "link": "/en/appendices/h-advanced-index"
        }
      ]
    }
  ],
  sidebar: {
    "/en/preface/": enBookSidebar,
    "/en/part-01/": enBookSidebar,
    "/en/part-02/": enBookSidebar,
    "/en/part-03/": enBookSidebar,
    "/en/part-04/": enBookSidebar,
    "/en/part-05/": enBookSidebar,
    "/en/part-06/": enBookSidebar,
    "/en/part-07/": enBookSidebar,
    "/en/appendices/": enBookSidebar,
    "/en/glossary": enBookSidebar,
    "/en/solutions/": enSolutionsSidebar
  }
} as const

const zhBookSidebar = [
  {
    "text": "开始阅读",
    "items": [
      {
        "text": "F# 思维",
        "link": "/zh/"
      },
      {
        "text": "前言：如何使用本书",
        "link": "/zh/preface/"
      }
    ]
  },
  {
    "text": "第一部分 · 表达式与函数",
    "collapsed": true,
    "items": [
      {
        "text": "第 1 章：第一次 F# 会话",
        "link": "/zh/part-01/ch-01-first-session"
      },
      {
        "text": "第 2 章：值、绑定与表达式",
        "link": "/zh/part-01/ch-02-values-bindings-expressions"
      },
      {
        "text": "第 3 章：函数也是值",
        "link": "/zh/part-01/ch-03-functions-as-values"
      },
      {
        "text": "第 4 章：分支与基本模式",
        "link": "/zh/part-01/ch-04-branching-patterns"
      },
      {
        "text": "第 5 章：列表、管道与数据流",
        "link": "/zh/part-01/ch-05-lists-pipelines"
      },
      {
        "text": "第 6 章：递归、尾调用与折叠",
        "link": "/zh/part-01/ch-06-recursion-folds"
      }
    ]
  },
  {
    "text": "第二部分 · 用类型建立模型",
    "collapsed": true,
    "items": [
      {
        "text": "第 7 章：记录、更新、相等与比较",
        "link": "/zh/part-02/ch-07-records-equality"
      },
      {
        "text": "第 8 章：可辨识联合与状态建模",
        "link": "/zh/part-02/ch-08-discriminated-unions"
      },
      {
        "text": "第 9 章：缺失与预期失败",
        "link": "/zh/part-02/ch-09-option-result"
      },
      {
        "text": "第 10 章：递归类型与结构递归",
        "link": "/zh/part-02/ch-10-recursive-types"
      },
      {
        "text": "第 11 章：泛型、约束与度量单位",
        "link": "/zh/part-02/ch-11-generics-constraints"
      },
      {
        "text": "第 12 章：让非法状态无法表示",
        "link": "/zh/part-02/ch-12-making-illegal-states-unrepresentable"
      }
    ]
  },
  {
    "text": "第三部分 · 组合与程序结构",
    "collapsed": true,
    "items": [
      {
        "text": "第 13 章：组合、参数顺序与管道 API",
        "link": "/zh/part-03/ch-13-composition-pipeline-api"
      },
      {
        "text": "第 14 章：集合选择与求值模型",
        "link": "/zh/part-03/ch-14-collections-evaluation"
      },
      {
        "text": "第 15 章：活动模式与领域匹配边界",
        "link": "/zh/part-03/ch-15-active-patterns"
      },
      {
        "text": "第 16 章：模块、命名空间、项目与编译设置",
        "link": "/zh/part-03/ch-16-modules-namespaces-projects"
      },
      {
        "text": "第 17 章：签名、访问控制与面向 F# 的 API",
        "link": "/zh/part-03/ch-17-signatures-encapsulation"
      },
      {
        "text": "第 18 章：显式工作流组合与验证累积",
        "link": "/zh/part-03/ch-18-workflow-validation"
      }
    ]
  },
  {
    "text": "第四部分 · 副作用、异步与并发",
    "collapsed": true,
    "items": [
      {
        "text": "第 19 章：.NET API 与空值边界",
        "link": "/zh/part-04/ch-19-dotnet-null-boundaries"
      },
      {
        "text": "第 20 章：函数式核心与副作用边界",
        "link": "/zh/part-04/ch-20-functional-core-effects"
      },
      {
        "text": "第 21 章：异常、资源与 I/O",
        "link": "/zh/part-04/ch-21-exceptions-resources-io"
      },
      {
        "text": "第 22 章：Async<'T> 与 Task<'T>",
        "link": "/zh/part-04/ch-22-async-task"
      },
      {
        "text": "第 23 章：取消、超时、故障与释放",
        "link": "/zh/part-04/ch-23-cancellation-timeouts"
      },
      {
        "text": "第 24 章：并行、并发、代理与受控可变性",
        "link": "/zh/part-04/ch-24-concurrency-agents-state"
      }
    ]
  },
  {
    "text": "第五部分 · .NET 互操作与工程质量",
    "collapsed": true,
    "items": [
      {
        "text": "第 25 章：在 F# 中定义对象",
        "link": "/zh/part-05/ch-25-objects-interfaces"
      },
      {
        "text": "第 26 章：深入 .NET 边界",
        "link": "/zh/part-05/ch-26-dotnet-runtime-boundaries"
      },
      {
        "text": "第 27 章：为 C# 设计 F# API",
        "link": "/zh/part-05/ch-27-fsharp-api-for-csharp"
      },
      {
        "text": "第 28 章：示例测试、替身与边界测试",
        "link": "/zh/part-05/ch-28-testing-boundaries"
      },
      {
        "text": "第 29 章：使用 FsCheck 进行性质测试",
        "link": "/zh/part-05/ch-29-property-testing"
      },
      {
        "text": "第 30 章：诊断、调试、格式化与构建",
        "link": "/zh/part-05/ch-30-diagnostics-tooling-builds"
      },
      {
        "text": "第 31 章：先测量再优化",
        "link": "/zh/part-05/ch-31-measure-before-optimizing"
      },
      {
        "text": "第 32 章：从函数到应用",
        "link": "/zh/part-05/ch-32-functions-to-applications"
      }
    ]
  },
  {
    "text": "第六部分 · 活动预约系统",
    "collapsed": true,
    "items": [
      {
        "text": "第 33 章：业务语言、命令、事件与模型",
        "link": "/zh/part-06/ch-33-domain-language-model"
      },
      {
        "text": "第 34 章：纯预约工作流与验证",
        "link": "/zh/part-06/ch-34-pure-booking-workflow"
      },
      {
        "text": "第 35 章：端口、持久化、配置与替身",
        "link": "/zh/part-06/ch-35-ports-persistence-config"
      },
      {
        "text": "第 36 章：Web API、JSON 与输入边界",
        "link": "/zh/part-06/ch-36-web-api-boundaries"
      },
      {
        "text": "第 37 章：一致性、幂等、重试与部分失败",
        "link": "/zh/part-06/ch-37-consistency-idempotency"
      },
      {
        "text": "第 38 章：集成、诊断、C# 客户端与发布证据",
        "link": "/zh/part-06/ch-38-integration-diagnostics-release"
      }
    ]
  },
  {
    "text": "第七部分 · 生态地图",
    "collapsed": true,
    "items": [
      {
        "text": "第 39 章：ASP.NET Core 与 F# Web 生态",
        "link": "/zh/part-07/ch-39-web-ecosystem"
      },
      {
        "text": "第 40 章：数据、类型提供器、分析与机器学习",
        "link": "/zh/part-07/ch-40-data-analytics"
      },
      {
        "text": "第 41 章：Fable、Elmish 与浏览器应用",
        "link": "/zh/part-07/ch-41-fable-elmish"
      },
      {
        "text": "第 42 章：云、容器、Serverless 与 .NET Aspire",
        "link": "/zh/part-07/ch-42-cloud-containers-aspire"
      },
      {
        "text": "第 43 章：Avalonia、桌面端与移动端",
        "link": "/zh/part-07/ch-43-avalonia-desktop-mobile"
      },
      {
        "text": "第 44 章：Unity 6.3 LTS 与 F#",
        "link": "/zh/part-07/ch-44-unity"
      },
      {
        "text": "第 45 章：脚本、自动化、包生态与继续学习",
        "link": "/zh/part-07/ch-45-scripting-packages-next"
      }
    ]
  },
  {
    "text": "参考资料",
    "collapsed": true,
    "items": [
      {
        "text": "附录 A：跨平台环境配置",
        "link": "/zh/appendices/a-setup"
      },
      {
        "text": "附录 B：语法与运算符速查",
        "link": "/zh/appendices/b-syntax-reference"
      },
      {
        "text": "附录 C：集合选择与复杂度",
        "link": "/zh/appendices/c-collections"
      },
      {
        "text": "附录 D：从 C# 迁移到 F# 与互操作",
        "link": "/zh/appendices/d-csharp-migration"
      },
      {
        "text": "附录 E：常见编译器诊断索引",
        "link": "/zh/appendices/e-compiler-errors"
      },
      {
        "text": "附录 F：F# 中英文术语表",
        "link": "/zh/glossary"
      },
      {
        "text": "附录 G：答案与开放题评审指南",
        "link": "/zh/appendices/g-solutions-guide"
      },
      {
        "text": "附录 H：高级特性识别索引",
        "link": "/zh/appendices/h-advanced-index"
      }
    ]
  }
] as const

const zhSolutionsSidebar = [
  {
    "text": "练习答案",
    "items": [
      {
        "text": "附录 G：答案与开放题评审指南",
        "link": "/zh/appendices/g-solutions-guide"
      },
      {
        "text": "第 1 章练习答案",
        "link": "/zh/solutions/ch-01-first-session"
      },
      {
        "text": "第 2 章练习答案",
        "link": "/zh/solutions/ch-02-values-bindings-expressions"
      },
      {
        "text": "第 3 章练习答案",
        "link": "/zh/solutions/ch-03-functions-as-values"
      },
      {
        "text": "第 4 章练习答案",
        "link": "/zh/solutions/ch-04-branching-patterns"
      },
      {
        "text": "第 5 章练习答案",
        "link": "/zh/solutions/ch-05-lists-pipelines"
      },
      {
        "text": "第 6 章练习答案",
        "link": "/zh/solutions/ch-06-recursion-folds"
      },
      {
        "text": "第 7 章练习答案",
        "link": "/zh/solutions/ch-07-records-equality"
      },
      {
        "text": "第 8 章练习答案",
        "link": "/zh/solutions/ch-08-discriminated-unions"
      },
      {
        "text": "第 9 章练习答案",
        "link": "/zh/solutions/ch-09-option-result"
      },
      {
        "text": "第 10 章练习答案",
        "link": "/zh/solutions/ch-10-recursive-types"
      },
      {
        "text": "第 11 章练习答案",
        "link": "/zh/solutions/ch-11-generics-constraints"
      },
      {
        "text": "第 12 章练习答案",
        "link": "/zh/solutions/ch-12-making-illegal-states-unrepresentable"
      },
      {
        "text": "第 13 章练习答案",
        "link": "/zh/solutions/ch-13-composition-pipeline-api"
      },
      {
        "text": "第 14 章练习答案",
        "link": "/zh/solutions/ch-14-collections-evaluation"
      },
      {
        "text": "第 15 章练习答案",
        "link": "/zh/solutions/ch-15-active-patterns"
      },
      {
        "text": "第 16 章答案",
        "link": "/zh/solutions/ch-16-modules-namespaces-projects"
      },
      {
        "text": "第 17 章答案",
        "link": "/zh/solutions/ch-17-signatures-encapsulation"
      },
      {
        "text": "第 18 章答案",
        "link": "/zh/solutions/ch-18-workflow-validation"
      },
      {
        "text": "第 19 章答案",
        "link": "/zh/solutions/ch-19-dotnet-null-boundaries"
      },
      {
        "text": "第 20 章答案",
        "link": "/zh/solutions/ch-20-functional-core-effects"
      },
      {
        "text": "第 21 章答案",
        "link": "/zh/solutions/ch-21-exceptions-resources-io"
      },
      {
        "text": "第 22 章练习答案",
        "link": "/zh/solutions/ch-22-async-task"
      },
      {
        "text": "第 23 章练习答案",
        "link": "/zh/solutions/ch-23-cancellation-timeouts"
      },
      {
        "text": "第 24 章练习答案",
        "link": "/zh/solutions/ch-24-concurrency-agents-state"
      },
      {
        "text": "第 25 章答案",
        "link": "/zh/solutions/ch-25-objects-interfaces"
      },
      {
        "text": "第 26 章答案",
        "link": "/zh/solutions/ch-26-dotnet-runtime-boundaries"
      },
      {
        "text": "第 27 章练习答案",
        "link": "/zh/solutions/ch-27-fsharp-api-for-csharp"
      },
      {
        "text": "第 28 章练习答案",
        "link": "/zh/solutions/ch-28-testing-boundaries"
      },
      {
        "text": "第 29 章练习答案",
        "link": "/zh/solutions/ch-29-property-testing"
      },
      {
        "text": "第 30 章练习答案",
        "link": "/zh/solutions/ch-30-diagnostics-tooling-builds"
      },
      {
        "text": "第 31 章练习答案",
        "link": "/zh/solutions/ch-31-measure-before-optimizing"
      },
      {
        "text": "第 32 章练习答案",
        "link": "/zh/solutions/ch-32-functions-to-applications"
      },
      {
        "text": "第 33 章练习答案",
        "link": "/zh/solutions/ch-33-domain-language-model"
      },
      {
        "text": "第 34 章答案",
        "link": "/zh/solutions/ch-34-pure-booking-workflow"
      },
      {
        "text": "第 35 章答案",
        "link": "/zh/solutions/ch-35-ports-persistence-config"
      },
      {
        "text": "第 36 章答案",
        "link": "/zh/solutions/ch-36-web-api-boundaries"
      },
      {
        "text": "第 37 章答案",
        "link": "/zh/solutions/ch-37-consistency-idempotency"
      },
      {
        "text": "第 38 章练习答案",
        "link": "/zh/solutions/ch-38-integration-diagnostics-release"
      },
      {
        "text": "第 39 章练习答案",
        "link": "/zh/solutions/ch-39-web-ecosystem"
      },
      {
        "text": "第 40 章练习答案",
        "link": "/zh/solutions/ch-40-data-analytics"
      },
      {
        "text": "第 41 章练习答案",
        "link": "/zh/solutions/ch-41-fable-elmish"
      },
      {
        "text": "第 42 章练习答案",
        "link": "/zh/solutions/ch-42-cloud-containers-aspire"
      },
      {
        "text": "第 43 章练习答案",
        "link": "/zh/solutions/ch-43-avalonia-desktop-mobile"
      },
      {
        "text": "第 44 章练习答案",
        "link": "/zh/solutions/ch-44-unity"
      },
      {
        "text": "第 45 章练习答案",
        "link": "/zh/solutions/ch-45-scripting-packages-next"
      }
    ]
  }
] as const

export const zhNavigation = {
  nav: [
    {
      "text": "首页",
      "link": "/zh/"
    },
    {
      "text": "前言与阅读路线",
      "link": "/zh/preface/"
    },
    {
      "text": "开始阅读",
      "link": "/zh/part-01/ch-01-first-session"
    },
    {
      "text": "参考资料",
      "items": [
        {
          "text": "附录 A：跨平台环境配置",
          "link": "/zh/appendices/a-setup"
        },
        {
          "text": "附录 B：语法与运算符速查",
          "link": "/zh/appendices/b-syntax-reference"
        },
        {
          "text": "附录 C：集合选择与复杂度",
          "link": "/zh/appendices/c-collections"
        },
        {
          "text": "附录 D：从 C# 迁移到 F# 与互操作",
          "link": "/zh/appendices/d-csharp-migration"
        },
        {
          "text": "附录 E：常见编译器诊断索引",
          "link": "/zh/appendices/e-compiler-errors"
        },
        {
          "text": "附录 F：F# 中英文术语表",
          "link": "/zh/glossary"
        },
        {
          "text": "附录 G：答案与开放题评审指南",
          "link": "/zh/appendices/g-solutions-guide"
        },
        {
          "text": "附录 H：高级特性识别索引",
          "link": "/zh/appendices/h-advanced-index"
        }
      ]
    }
  ],
  sidebar: {
    "/zh/preface/": zhBookSidebar,
    "/zh/part-01/": zhBookSidebar,
    "/zh/part-02/": zhBookSidebar,
    "/zh/part-03/": zhBookSidebar,
    "/zh/part-04/": zhBookSidebar,
    "/zh/part-05/": zhBookSidebar,
    "/zh/part-06/": zhBookSidebar,
    "/zh/part-07/": zhBookSidebar,
    "/zh/appendices/": zhBookSidebar,
    "/zh/glossary": zhBookSidebar,
    "/zh/solutions/": zhSolutionsSidebar
  }
} as const
