<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Configuration.fs" />
    <Compile Include="FileStore.fs" />
    <Compile Include="PaymentStub.fs" />
    <Compile Include="NotificationStub.fs" />
    <Compile Include="Composition.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Booking.Domain/Booking.Domain.fsproj" />
    <ProjectReference Include="../Booking.Contracts/Booking.Contracts.fsproj" />
  </ItemGroup>
</Project>
