<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Consumer.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../chapters/ch17/Ch17.fsproj" />
  </ItemGroup>
</Project>
